name: diginews_fazar
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # Navigation & Service Locator
  go_router: ^14.0.0
  get_it: ^7.6.0

  # State Management & Network
  flutter_bloc: ^8.1.3
  dio: ^5.4.0

  # Local Database (Isar)
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1

  # Integrasi Tambahan
  lottie: ^3.1.0
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generator untuk Isar & Mocking untuk Unit Test
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8
  mocktail: ^1.0.4

  # Icons & Lints
  cupertino_icons: ^1.0.8
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/easter_egg.json