# Mengatur memori agar pas dan tidak membuat sistem Windows membunuh Gradle secara paksa
org.gradle.jvmargs=-Xmx2560m -XX:MaxMetaspaceSize=768m -XX:+HeapDumpOnOutOfMemoryError

# Mengaktifkan fitur AndroidX untuk mengatasi error kompilasi pustaka isar/jni
android.useAndroidX=true
android.enableJetifier=true

# Optimalisasi performa build lokal
org.gradle.parallel=true
org.gradle.caching=true