name: Flutter CI/CD - Test and Build Release APK

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test_and_build:
    name: Run Unit Tests & Build Production APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java Development Kit (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Unit Tests
        run: flutter test

      - name: Build APK Release
        run: flutter build apk --release --no-tree-shake-icons --build-name=1.0.0 --build-number=1